### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by rstormsf** [j-mcnally/ansible-rails#2]
Few things to explain would be really helpful

```
servers:
      - region_id: 8
        size_id: 63
        image_id: 7053293
        internal_id: apps.1
```

how to find those values and understand for future users of repo

another confusion is with ssh keys I think is that in `ansible.cfg` we have:

```
[defaults]
private_key_file=~/.ssh/myapp.pem
```

then we have in 
`extra/capistrano/deploy.rb`

```
17:  keys: ["#{ENV['HOME']}/.ssh/private_key.pem"]
```

but in README.md:

```
Configure SSH private / public keys
~/.ssh/app_private_key.pem
```
